Global:
  use_gpu: True
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/mv3_none_bilstm_ctc/
  save_epoch_step: 10
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 500]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: true
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: ppocr/utils/dict/chinese_cht_dict.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_mv3_none_bilstm_ctc.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  in_channels: 6
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: LMDBDataSet
    data_dir: ../../experiment/datasets/TCSynth
    limit: 0.02
    # name: SimpleDataSet
    # data_dir: ../../experiment/datasets/TC-STR
    # label_file_list:
    # - ../../experiment/datasets/TC-STR/all_labels.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SSRaug:
          image_shape: [3, 32, 100]
          mode: 'append'
          output_channel: -1   
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - SSRaug:
          image_shape: [3, 32, 100]
          mode: 'append'
          output_channel: -1
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: true
    batch_size_per_card: 256
    drop_last: true
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../../experiment/datasets/TC-STR
    label_file_list:
    - ../../experiment/datasets/TC-STR/test_labels.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SSRaug:
          image_shape: [3, 32, 100]
          mode: 'append'
          output_channel: -1          
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - SSRaug:
          image_shape: [3, 32, 100]
          mode: 'append'
          output_channel: -1          
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 4
